"use client";
import type { Metadata } from "next";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Inter } from "next/font/google";
import { ThemeContextWrapper } from "./contexts/ThemeContext";
import "./styles/globals.css";
import "./styles/mainScreen.css";
import "./styles/dashboard.css";
import "./styles/register.css";
import "./styles/scenes.css";
import "./styles/profile.css";
import "./styles/tabs.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Chat",
//   description: "Generated by create next app",
// };
const queryClient = new QueryClient();
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
        <ThemeContextWrapper>
          <body className={inter.className}>{children}</body>
        </ThemeContextWrapper>
      </QueryClientProvider>
    </html>
  );
}
